spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness2
    username: postgres
    password: System

  jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect 

server:
   port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: http://localhost:8181
  realm: fitness-oauth2
  resource: admin-cli
  admin:
    username: admin
    password: admin
